/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: bigint;
    title: string;
    createdAt: Time;
    completed: boolean;
    dueDate?: Time;
    description: string;
}
export interface TimetableSlot {
    id: bigint;
    startTime: bigint;
    subject: string;
    dayOfWeek: string;
    createdAt: Time;
    durationMinutes: bigint;
    location: string;
}
export interface ChatMessage {
    id: bigint;
    content: string;
    sender: string;
    timestamp: Time;
}
export type Time = bigint;
export interface SidebarItem {
    id: bigint;
    title: string;
    icon: string;
    route: string;
}
export interface DayEntry {
    id: bigint;
    userId: string;
    date: bigint;
    createdAt: Time;
    taskDescription: string;
}
export interface backendInterface {
    /**
     * / Add a new day entry with the given details.
     * / Returns the newly created DayEntry.
     */
    addDayEntry(userId: string, date: bigint, taskDescription: string): Promise<DayEntry>;
    addSidebarItem(title: string, icon: string, route: string): Promise<SidebarItem>;
    createSlot(subject: string, startTime: bigint, location: string, dayOfWeek: string, durationMinutes: bigint): Promise<TimetableSlot>;
    createTask(title: string, dueDate: Time | null, description: string): Promise<Task>;
    /**
     * / Delete a day entry by its ID.
     */
    deleteDayEntry(entryId: bigint): Promise<void>;
    deleteSlot(slotId: bigint): Promise<void>;
    getAllMessages(): Promise<Array<ChatMessage>>;
    getAllSidebarItems(): Promise<Array<SidebarItem>>;
    getAllSlots(): Promise<Array<TimetableSlot>>;
    getAllTasks(): Promise<Array<Task>>;
    /**
     * / Get all day entries for a specific user.
     */
    getDayEntries(userId: string): Promise<Array<DayEntry>>;
    /**
     * / Get day entries for a user within a specific date range.
     */
    getDayEntriesByRange(userId: string, startDate: bigint, endDate: bigint): Promise<Array<DayEntry>>;
    markTaskAsCompleted(taskId: bigint): Promise<void>;
    sendMessage(sender: string, content: string): Promise<ChatMessage>;
    /**
     * / Update the task description of an existing day entry.
     */
    updateDayEntry(entryId: bigint, newDescription: string): Promise<DayEntry>;
}
import type { Task as _Task, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDayEntry(arg0: string, arg1: bigint, arg2: string): Promise<DayEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addDayEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDayEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addSidebarItem(arg0: string, arg1: string, arg2: string): Promise<SidebarItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addSidebarItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSidebarItem(arg0, arg1, arg2);
            return result;
        }
    }
    async createSlot(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: bigint): Promise<TimetableSlot> {
        if (this.processError) {
            try {
                const result = await this.actor.createSlot(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSlot(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createTask(arg0: string, arg1: Time | null, arg2: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Task_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Task_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDayEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDayEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDayEntry(arg0);
            return result;
        }
    }
    async deleteSlot(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSlot(arg0);
            return result;
        }
    }
    async getAllMessages(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMessages();
            return result;
        }
    }
    async getAllSidebarItems(): Promise<Array<SidebarItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSidebarItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSidebarItems();
            return result;
        }
    }
    async getAllSlots(): Promise<Array<TimetableSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSlots();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSlots();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDayEntries(arg0: string): Promise<Array<DayEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayEntries(arg0);
            return result;
        }
    }
    async getDayEntriesByRange(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<DayEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDayEntriesByRange(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDayEntriesByRange(arg0, arg1, arg2);
            return result;
        }
    }
    async markTaskAsCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTaskAsCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTaskAsCompleted(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async updateDayEntry(arg0: bigint, arg1: string): Promise<DayEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDayEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDayEntry(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Task_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    createdAt: _Time;
    completed: boolean;
    dueDate: [] | [_Time];
    description: string;
}): {
    id: bigint;
    title: string;
    createdAt: Time;
    completed: boolean;
    dueDate?: Time;
    description: string;
} {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.dueDate)),
        description: value.description
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
