/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const DayEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Text,
  'date' : IDL.Int,
  'createdAt' : Time,
  'taskDescription' : IDL.Text,
});
export const SidebarItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'route' : IDL.Text,
});
export const TimetableSlot = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'subject' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'createdAt' : Time,
  'durationMinutes' : IDL.Nat,
  'location' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'description' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addDayEntry' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [DayEntry], []),
  'addSidebarItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SidebarItem],
      [],
    ),
  'createSlot' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Nat],
      [TimetableSlot],
      [],
    ),
  'createTask' : IDL.Func([IDL.Text, IDL.Opt(Time), IDL.Text], [Task], []),
  'deleteDayEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteSlot' : IDL.Func([IDL.Nat], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getAllSidebarItems' : IDL.Func([], [IDL.Vec(SidebarItem)], ['query']),
  'getAllSlots' : IDL.Func([], [IDL.Vec(TimetableSlot)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getDayEntries' : IDL.Func([IDL.Text], [IDL.Vec(DayEntry)], ['query']),
  'getDayEntriesByRange' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [IDL.Vec(DayEntry)],
      ['query'],
    ),
  'markTaskAsCompleted' : IDL.Func([IDL.Nat], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [ChatMessage], []),
  'updateDayEntry' : IDL.Func([IDL.Nat, IDL.Text], [DayEntry], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const DayEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Text,
    'date' : IDL.Int,
    'createdAt' : Time,
    'taskDescription' : IDL.Text,
  });
  const SidebarItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'route' : IDL.Text,
  });
  const TimetableSlot = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'subject' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'createdAt' : Time,
    'durationMinutes' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'description' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addDayEntry' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [DayEntry], []),
    'addSidebarItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SidebarItem],
        [],
      ),
    'createSlot' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Nat],
        [TimetableSlot],
        [],
      ),
    'createTask' : IDL.Func([IDL.Text, IDL.Opt(Time), IDL.Text], [Task], []),
    'deleteDayEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteSlot' : IDL.Func([IDL.Nat], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getAllSidebarItems' : IDL.Func([], [IDL.Vec(SidebarItem)], ['query']),
    'getAllSlots' : IDL.Func([], [IDL.Vec(TimetableSlot)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getDayEntries' : IDL.Func([IDL.Text], [IDL.Vec(DayEntry)], ['query']),
    'getDayEntriesByRange' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [IDL.Vec(DayEntry)],
        ['query'],
      ),
    'markTaskAsCompleted' : IDL.Func([IDL.Nat], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [ChatMessage], []),
    'updateDayEntry' : IDL.Func([IDL.Nat, IDL.Text], [DayEntry], []),
  });
};

export const init = ({ IDL }) => { return []; };