/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
}
export interface DayEntry {
  'id' : bigint,
  'userId' : string,
  'date' : bigint,
  'createdAt' : Time,
  'taskDescription' : string,
}
export interface SidebarItem {
  'id' : bigint,
  'title' : string,
  'icon' : string,
  'route' : string,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
}
export type Time = bigint;
export interface TimetableSlot {
  'id' : bigint,
  'startTime' : bigint,
  'subject' : string,
  'dayOfWeek' : string,
  'createdAt' : Time,
  'durationMinutes' : bigint,
  'location' : string,
}
export interface _SERVICE {
  /**
   * / Add a new day entry with the given details.
   * / Returns the newly created DayEntry.
   */
  'addDayEntry' : ActorMethod<[string, bigint, string], DayEntry>,
  'addSidebarItem' : ActorMethod<[string, string, string], SidebarItem>,
  'createSlot' : ActorMethod<
    [string, bigint, string, string, bigint],
    TimetableSlot
  >,
  'createTask' : ActorMethod<[string, [] | [Time], string], Task>,
  /**
   * / Delete a day entry by its ID.
   */
  'deleteDayEntry' : ActorMethod<[bigint], undefined>,
  'deleteSlot' : ActorMethod<[bigint], undefined>,
  'getAllMessages' : ActorMethod<[], Array<ChatMessage>>,
  'getAllSidebarItems' : ActorMethod<[], Array<SidebarItem>>,
  'getAllSlots' : ActorMethod<[], Array<TimetableSlot>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  /**
   * / Get all day entries for a specific user.
   */
  'getDayEntries' : ActorMethod<[string], Array<DayEntry>>,
  /**
   * / Get day entries for a user within a specific date range.
   */
  'getDayEntriesByRange' : ActorMethod<
    [string, bigint, bigint],
    Array<DayEntry>
  >,
  'markTaskAsCompleted' : ActorMethod<[bigint], undefined>,
  'sendMessage' : ActorMethod<[string, string], ChatMessage>,
  /**
   * / Update the task description of an existing day entry.
   */
  'updateDayEntry' : ActorMethod<[bigint, string], DayEntry>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];